const cartActionTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
    DECREASE_QTY_AND_DELETE_ITEM: 'DECREASE_QTY_AND_DELETE_ITEM',
    DELETE_ITEM_FROM_CART: 'DELETE_ITEM_FROM_CART'
}

export default cartActionTypes