const cartActionTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
    DECREASE_QTY_AND_DELETE_ITEM: 'DECREASE_QTY_AND_DELETE_ITEM',
    DELETE_ITEM_FROM_CART: 'DELETE_ITEM_FROM_CART',
    CLEAR_CART: 'CLEAR_CART',
    SET_CART_FROM_FIREBASE: 'SET_CART_FROM_FIREBASE',
    UPDATE_CART_IN_FIREBASE: 'UPDATE_CART_IN_FIREBASE'
}

export default cartActionTypes